image:
  registry: mirror.gcr.io
  repository: bitnami/wordpress

mariadb:
  image:
    registry: mirror.gcr.io
    repository: bitnami/mariadb
  primary:
    persistence:
      storageClass: "longhorn"

global:
  storageClass: "longhorn"

ingress:
  enabled: false
