global:
  storageClass: "longhorn"
  imageRegistry: "docker.m.daocloud.io"  # <-- Wskazujemy precyzyjny podrejestr proxy dla Bitnami

image:
  registry: docker.m.daocloud.io
  repository: bitnami/wordpress

mariadb:
  image:
    registry: docker.m.daocloud.io
    repository: bitnami/mariadb
  primary:
    persistence:
      storageClass: "longhorn"

ingress:
  enabled: false
