global:
  storageClass: "longhorn"
  imageRegistry: "daocloud.io"  # <-- Zmiana mirroru na pełny mirror Docker Huba

image:
  registry: daocloud.io
  repository: bitnami/wordpress

mariadb:
  image:
    registry: daocloud.io
    repository: bitnami/mariadb
  primary:
    persistence:
      storageClass: "longhorn"

ingress:
  enabled: false
